server:
  port: 8081

spring:
  application:
    name: produto

  datasource:
    url: jdbc:postgresql://localhost:5432/produto
    username: produto
    password: root

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

file:
  upload-dir: /tmp